# Action runs using the credentials of the Evolv Bot app, which has been permitted to
# bypass branch protections on 'main'

name: Tag Build

on:
  repository_dispatch:
    types: ['elevated:pull_request.merged']

permissions:
  contents: write
  packages: read

jobs:
  tag:
    name: Tag Build
    if: github.event.client_payload.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ref
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Tag
        run: |
          npx --yes -- lerna version --yes
